name: 'covid_2021'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ===================================================================
# SEÇÃO 'MODELS' CORRIGIDA E FINAL
# Esta é a configuração que mapeia suas pastas para os schemas corretos
# e define a materialização ideal para cada camada.
# ===================================================================
models:
  covid_2021:
    
    # Modelos na pasta "staging" irão para o schema BRONZE como views
    staging:
      +materialized: view
      +schema: bronze

    # Modelos na pasta "intermediate" irão para o schema SILVER como views
    intermediate:
      +materialized: view
      +schema: silver

    # Modelos na pasta "dimensions" irão para o schema GOLD como tabelas
    dimensions:
      +materialized: table
      +schema: gold

    # Modelos na pasta "facts" irão para o schema GOLD como tabelas
    facts:
      +materialized: table
      +schema: gold
# ===================================================================
# FIM DA SEÇÃO 'MODELS'
# ===================================================================

on-run-start:
  - "{{ log('Iniciando execução do dbt em ' ~ run_started_at, info=true) }}"

on-run-end:
  - "{{ log('Execução do dbt finalizada em ' ~ run_started_at, info=true) }}"