version: 2

sources:
  - name: bronze_source
    database: COVID19
    schema: BRONZE
    description: "Fontes de dados brutos do sistema COVID19"
    meta:
      data_classification: "sensitive"
      source_system: "DataSUS"
    tables:
      - name: RAW_LEITO_OCUPACAO_2020
        description: "Dados brutos de ocupação de leitos - 2020"
      - name: RAW_LEITO_OCUPACAO_2021
        description: "Dados brutos de ocupação de leitos - 2021"
      - name: RAW_LEITO_OCUPACAO_2022
        description: "Dados brutos de ocupação de leitos - 2022"
      - name: RAW_MUNICIPIOS_IBGE
        description: "Dados de municípios brasileiros - IBGE"
      - name: RAW_ESTABELECIMENTOS_CNES
        description: "Dados de estabelecimentos de saúde - CNES"

models:
  - name: stg_leito_ocupacao_consolidado
    description: "Modelo de staging que consolida dados de ocupação de leitos de todos os anos (2020-2022)"
    meta:
      layer: "bronze"
      data_classification: "sensitive"
      test_strategy: "tolerant" # Permite alguns problemas menores na camada de staging
    columns:
      - name: id_registro
        description: "Identificador único do registro"
        tests:
          - unique:
              config:
                severity: warn  # Não bloqueia em staging
          - not_null:
              config:
                severity: warn  # Não bloqueia em staging
      - name: data_notificacao
        description: "Data de notificação do registro"
        tests:
          - not_null:
              config:
                severity: warn  # Informativo apenas
      - name: cnes
        description: "Código do estabelecimento de saúde (CNES)"
        tests:
          - not_null:
              config:
                severity: warn  # Informativo apenas
      - name: ano_dados
        description: "Ano de origem dos dados"
        tests:
          - not_null  # Crítico para particionamento
          - accepted_values:
              values: [2020, 2021, 2022]
              config:
                severity: error  # Bloqueia se ano inválido

  - name: int_leitos_ocupacao_unificado
    description: "Modelo intermediário que enriquece dados de staging com chaves de dimensões"
    columns:
      - name: id_registro
        description: "Identificador único do registro"
        tests:
          - unique
          - not_null
      - name: id_localidade
        description: "Chave estrangeira para dimensão localidade"
        tests:
          - not_null
          - relationships:
              to: ref('dim_localidade')
              field: id_localidade

  - name: dim_tempo
    description: "Dimensão temporal com informações detalhadas sobre datas"
    meta:
      layer: "silver"
      data_classification: "public"
    columns:
      - name: id_tempo
        description: "Chave primária da dimensão tempo"
        tests:
          - unique
          - not_null
      - name: data_completa
        description: "Data no formato YYYY-MM-DD"
        tests:
          - unique
          - not_null
      - name: ano
        description: "Ano (YYYY)"
        tests:
          - not_null
      - name: mes
        description: "Mês (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: dia
        description: "Dia do mês (1-31)"
        tests:
          - not_null

  - name: dim_localidade
    description: "Dimensão geográfica com estados e municípios brasileiros"
    meta:
      layer: "silver"
      data_classification: "public"
    columns:
      - name: id_localidade
        description: "Chave primária da dimensão localidade"
        tests:
          - unique
          - not_null
      - name: estado
        description: "Nome do estado"
        tests:
          - not_null
      - name: municipio
        description: "Nome do município"
        tests:
          - not_null
      - name: localidade_completa
        description: "Descrição completa da localidade (município - estado)"
        tests:
          - not_null

  - name: dim_unidade_saude
    description: "Dimensão de unidades de saúde baseada no CNES"
    meta:
      layer: "silver"
      data_classification: "sensitive"
    columns:
      - name: id_unidade_saude
        description: "Chave primária da dimensão unidade de saúde"
        tests:
          - unique
          - not_null
      - name: cnes
        description: "Código CNES da unidade"
        tests:
          - unique
          - not_null
      - name: nome_unidade
        description: "Nome da unidade de saúde"
        tests:
          - not_null

  - name: dim_ocupacao_tipo
    description: "Dimensão de tipos de ocupação de leitos"
    meta:
      layer: "silver"
      data_classification: "public"
    columns:
      - name: id_ocupacao_tipo
        description: "Chave primária da dimensão tipo de ocupação"
        tests:
          - unique
          - not_null
      - name: tipo_ocupacao
        description: "Tipo de ocupação do leito"
        tests:
          - not_null

  - name: dim_cnes
    description: "Dimensão de estabelecimentos CNES"
    meta:
      layer: "silver"
      data_classification: "sensitive"
    columns:
      - name: id_cnes
        description: "Chave primária da dimensão CNES"
        tests:
          - unique
          - not_null
      - name: cnes
        description: "Código CNES"
        tests:
          - unique
          - not_null

  - name: fact_ocupacao_leitos
    description: "Tabela fato principal com dados de ocupação de leitos"
    meta:
      layer: "gold"
      data_classification: "sensitive"
      test_strategy: "strict" # Testes rigorosos na camada gold
    columns:
      - name: id_fato
        description: "Chave primária da tabela fato"
        tests:
          - unique
          - not_null
      - name: id_tempo
        description: "Chave estrangeira para dimensão tempo"
        tests:
          - not_null
          - relationships:
              to: ref('dim_tempo')
              field: id_tempo
      - name: id_localidade
        description: "Chave estrangeira para dimensão localidade"
        tests:
          - not_null
          - relationships:
              to: ref('dim_localidade')
              field: id_localidade
      - name: id_unidade_saude
        description: "Chave estrangeira para dimensão unidade de saúde"
        tests:
          - not_null
          - relationships:
              to: ref('dim_unidade_saude')
              field: id_unidade_saude
      - name: leitos_covid_ocupados
        description: "Número de leitos COVID ocupados"
        tests:
          - not_null
      - name: leitos_covid_livres
        description: "Número de leitos COVID livres"
        tests:
          - not_null
      - name: leitos_uti_ocupados
        description: "Número de leitos UTI ocupados"
        tests:
          - not_null
      - name: leitos_uti_livres
        description: "Número de leitos UTI livres"
        tests:
          - not_null
      - name: taxa_ocupacao_covid
        description: "Taxa de ocupação de leitos COVID (%)"
        tests:
          - not_null
      - name: taxa_ocupacao_uti
        description: "Taxa de ocupação de leitos UTI (%)"
        tests:
          - not_null
