# models/covid_2021/staging/sources.yml
version: 2

sources:
  - name: bronze_source # Um nome para o seu grupo de fontes
    database: COVID_2021
    schema: BRONZE
    tables:
      # IMPORTANTE: Substitua o nome abaixo pelo nome REAL da sua tabela bruta no Snowflake
      - name: 'RAW_LEITO_OCUPACAO_2021'

       # Adicione aqui as outras tabelas brutas (municipios, cnes) quando as carregar
      - name: 'RAW_MUNICIPIOS_IBGE'
      - name: 'RAW_ESTABELECIMENTOS_CNES' # <-- A tabela que acabamos de carregar
