name: Deploy dbt Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt and dependencies
        run: |
          pip install dbt-snowflake
          dbt deps

      # --- NOVO PASSO ADICIONADO AQUI ---
      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "config:" > ~/.dbt/profiles.yml
          echo "  send_anonymous_usage_stats: False" >> ~/.dbt/profiles.yml
          echo "" >> ~/.dbt/profiles.yml
          echo "COVID19:" >> ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: dummy" >> ~/.dbt/profiles.yml
          echo "      user: dummy" >> ~/.dbt/profiles.yml
          echo "      password: dummy" >> ~/.dbt/profiles.yml
          echo "      role: dummy" >> ~/.dbt/profiles.yml
          echo "      database: dummy" >> ~/.dbt/profiles.yml
          echo "      warehouse: dummy" >> ~/.dbt/profiles.yml
          echo "      schema: dummy" >> ~/.dbt/profiles.yml
          echo "      threads: 1" >> ~/.dbt/profiles.yml

      - name: Generate dbt docs
        run: dbt docs generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DBT_GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'adsmbr'
          user_email: 'alissonmontijo@gmail.com'
